services:
  scrapper:
    build:
      context: scrapper
      dockerfile: Dockerfile
    restart: no
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=replace-admin
      - MONGO_INITDB_ROOT_PASSWORD=replace-password

    ports:
      - 127.0.0.1:8888:27017

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: no
    ports:
      - 127.0.0.1:8050:8050
    depends_on:
      scrapper:
        condition: service_completed_successfully
